<?php
/**
 * Serves /llms.txt only when an editor has enabled the stored body.
 *
 * The request does not call a model.
 *
 * @package QueryNova
 */

declare(strict_types=1);

namespace QueryNova\Modules\Ai\Presentation;

use QueryNova\Core\Contracts\HookSubscriberInterface;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

final class LlmsFrontend implements HookSubscriberInterface {

    public function hooks(): array {
        return [
            'init'              => [ 'registerRewrites', 1, 0 ],
            'query_vars'        => [ 'queryVars', 10, 1 ],
            'template_redirect' => [ 'serve', 0, 0 ],
        ];
    }

    public function hookType( string $hook ): string {
        return $hook === 'query_vars' ? 'filter' : 'action';
    }

    public function enabled(): bool {
        return get_option( 'querynova_llms_txt', 'no' ) === 'yes' && is_string( get_option( 'querynova_llms_body', '' ) ) && get_option( 'querynova_llms_body', '' ) !== '';
    }

    public function registerRewrites(): void {
        if ( ! $this->enabled() || ! function_exists( 'add_rewrite_rule' ) ) {
            return;
        }
        add_rewrite_rule( '^llms\.txt$', 'index.php?querynova_llms=1', 'top' );
    }

    /**
     * @param list<string> $vars
     * @return list<string>
     */
    public function queryVars( array $vars ): array {
        $vars[] = 'querynova_llms';

        return $vars;
    }

    public function serve(): void {
        if ( ! $this->enabled() || ! function_exists( 'get_query_var' ) ) {
            return;
        }
        $flag = get_query_var( 'querynova_llms' );
        if ( $flag !== '1' && $flag !== 1 ) {
            return;
        }
        $body = get_option( 'querynova_llms_body', '' );
        if ( ! is_string( $body ) || $body === '' ) {
            return;
        }
        if ( ! headers_sent() ) {
            header( 'Content-Type: text/plain; charset=utf-8' );
        }
        echo $body; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- stored llms.txt is plain text generated by QueryNova.
        exit;
    }
}
